drop table if exists member CASCADE;

create table member (
 id bigint generated by default as identity,
 member_name varchar(255),
 password varchar(255),
 nick_name varchar(255),
 primary key (id)
);
drop table if exists post CASCADE;
create table post (
 postid bigint generated by default as identity,
 memberid bigint,
 name varchar(255),
 storedname varchar(255),
 contents Longtext,
 primary key (postid)
);
drop table if exists follow CASCADE;
create table follow (
 following bigint,
 follower bigint
);